apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app-anan
  template:
    metadata:
      labels:
        app: nodejs-app-anan
    spec:
      containers:
      - name: nodejs-app
        image: 784699301512.dkr.ecr.us-east-1.amazonaws.com/anan-repo
        ports:
        - containerPort: 3000

